---
- name: Install on server
  hosts: localhost
  become: yes
  gather_facts: yes

  vars:
    docker_repo_key_url: https://download.docker.com/linux/debian/gpg
    docker_apt_repository: "deb [arch=amd64] https://download.docker.com/linux/debian bookworm stable"
    docker_compose_version: "v2.29.6"
    docker_compose_path: /usr/local/bin/docker-compose
    home_dir: /root

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    # Docker installation
    - name: Add Docker GPG key
      apt_key:
        url: "{{ docker_repo_key_url }}"
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "{{ docker_apt_repository }}"
        state: present
        filename: docker-ce

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: present

    - name: Ensure Docker service is started and enabled
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Get OS type (uname -s)
      command: uname -s
      register: os_type
      changed_when: false

    - name: Get architecture (uname -m)
      command: uname -m
      register: arch_type
      changed_when: false

    - name: Download Docker Compose binary
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ os_type.stdout }}-{{ arch_type.stdout }}"
        dest: "{{ docker_compose_path }}"
        mode: '0755'
    - name: Verify Docker Compose installation
      command: "{{ docker_compose_path }} --version"
      register: docker_compose_check
      changed_when: false

    - name: Show Docker Compose version
      debug:
        msg: "Docker Compose installed: {{ docker_compose_check.stdout }}"

    # Post-installation: Add user to docker group
    - name: Add current user to docker group
      user:
        name: "{{ ansible_user_id | default(ansible_user) | default('ubuntu') }}"
        groups: docker
        append: yes
    
    - name: install ZSH
      apt:
        name:
          - zsh
          - fonts-font-awesome
        state: present
    
    - name: Download Oh my ZSH
      get_url:
        url: "https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
        dest: "{{ home_dir }}"
        mode: '0755'
    
    - name: install oh my zsh
      shell: "{{ home_dir }}/install.sh -y"
      become: no

    - name: ZSH auto-suggestions download
      command: git clone https://github.com/zsh-users/zsh-autosuggestions.git {{ home_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions
      become: no

    - name: ZSH syntax highlighting download
      command: git clone https://github.com/zsh-users/zsh-syntax-highlighting.git {{ home_dir }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
      become: no

    - name: powerlevel10k
      command: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git {{ home_dir }}/.oh-my-zsh/custom}/themes/powerlevel10k
      become: no

    - name: upd plugin
      shell: "sed -i 's/plugins=(git)/plugins=(git zsh-autosuggestions zsh-syntax-highlighting)/' {{ home_dir }}/.zshrc"
      become: no
  
    - name: upd theme
      shell: sed -i 's|ZSH_THEME="robbyrussell"|ZSH_THEME="powerlevel10k/powerlevel10k"|' {{ home_dir }}/.zshrc
      become: no
    
    - name: upd theme
      shell: chsh -s $(which zsh)
      become: no

    - name: Print completion message
      debug:
        msg: |
          Installation completed!